[package]
name = "johnnybt_polars"
version = "0.1.0"
edition = "2021"

[lib]
name = "johnnybt_polars"
crate-type = ["cdylib"]

[dependencies]
polars = { version = "0.55.1", features = ["dtype-date", "dtype-struct", "temporal"], default-features = false }
pyo3 = { version = "0.29", features = ["abi3-py311"] }
pyo3-polars = { version = "0.28", features = ["derive"] }
serde = { version = "1", features = ["derive"] }

[profile.release]
lto = true
codegen-units = 1
